services:
  - type: web
    name: telegram-userbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: COMMAND_PREFIX
        value: "!"
      - key: COMMANDS_DIR
        value: "commands"
